### ISSUE TITLE
faltando tradução e possível erro de tradução

### ISSUE THREAD

**Issue by josueasas** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#10]
o "controles" não deveria se chamar centro de controles?
![Screenshot_2020-05-15-13-32-26-186_com microsoft emmx](https://user-images.githubusercontent.com/45245119/82076838-c749be80-96b4-11ea-8e09-e294a359ddf8.jpg)

e no feedback está faltando tradução para Control center
![Screenshot_2020-05-15-13-28-40-165_com miui bugreport](https://user-images.githubusercontent.com/45245119/82076990-04ae4c00-96b5-11ea-8476-59312218555a.jpg)

**Comment by RicardoGuariento** [comment]
@josueasas 
Eu dei como "Controles" para não ficar cortado, antes estava como "Central de Con...", estava estranho.
Quanto ao "control center" ali, eu não achei ele nos XMLs, nem no original em inglês,
