### ISSUE TITLE
ERRO TELA DE BLOQUEIO

### ISSUE THREAD

**Issue by fpdroso** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#12]
Percebi um bug na tela de bloqueio. Quando eu recebo notificação ou bloqueia o celular normalmente, parece que a brilho diminui quase no mínimo, aí é só desbloquear a tela que voltar no brilho normal

**Comment by bryangrobmann** [comment]
@fpdroso isso não é problema com tradução, esse tipo de problema deve ser reportado na xiaomi.eu
