### ISSUE TITLE
Erro de tradução

### ISSUE THREAD

**Issue by bryangrobmann** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#13]
Ricardo, como vai?

Acredito haver um erro de tradução na tela de gerenciamento de permissões dos Apps, onde está IMSI, não seria IMEI?

https://ibb.co/p132W8j

Abs.

**Comment by RicardoGuariento** [comment]
É isso mesmo
International Mobile Subscriber Identity (IMSI)
