### ISSUE TITLE
ERRO WIFI

### ISSUE THREAD

**Issue by ArthurVieira17** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#14]
**A conexão com WI-FI se desconecta sozinha a todo momento. Principalmente no Instagram e Youtube, porém as vezes tambem no uso Normal.**

**Comment by KcNirvana** [comment]
Boa tarde,
Isto é apenas um repositório de tradução.
Ponha esses erros no site da Xiaomi.
Obrigado.

Abraço
