### ISSUE TITLE
Despertador não tem opção de desligar 

### ISSUE THREAD

**Issue by marcellokarwalho** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#18]
Se estiver usando o celular e tocar o despertador, não há maneira de desligar. É preciso desligar o celular.

**Comment by RicardoGuariento** [comment]
Amigo, reporte isso no fórum da Xiaomi.eu. Eu cuido apenas da tradução da ROM, não tenho relação alguma com correção de bugs ou desenvolvimento.
