### ISSUE TITLE
Correção ortográfica MIUI 12

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#19]
Bom dia.
Segue um erro de sintaxe/ortográfico que encontrei dentro do app Segurança/verificação de vírus.
Redmi 6 Pro 
MIUI 12 Estável

Obrigado.
![IMG_20200811_101144](https://user-images.githubusercontent.com/44249272/89901280-461e9c80-dbbb-11ea-91ff-ee2a38f1499c.jpg)
![Screenshot_2020-08-13-17-40-35-649_com miui securitycenter](https://user-images.githubusercontent.com/44249272/90184975-59349680-dd8c-11ea-874e-7914ecd2578e.jpg)
Na segunda é a palavra "null"

**Comment by RicardoGuariento** [comment]
Corrigido!
