### ISSUE TITLE
Verificar a tradução de alguns itens

### ISSUE THREAD

**Issue by carlosviniciusg** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#22]
"Notificações e Centro de **Controlo**" em Configurações para "Notificações e Centro de **Controle**"
[https://ibb.co/nPpkWGX](url)

"Estilo e Centro de **Controlo**" em Notificações e Centro de Controlo para "Estilo e Centro de **Controle**"
"Itens mostrados no **ecrã** de bloqueio após deslizar para baixo" em Notificações e Centro de Controlo para "Itens mostrados na **tela** de bloqueio após deslizar para baixo"
[https://ibb.co/Bgq68tL](url)

**Comment by RicardoGuariento** [comment]
Corrigido!
