### ISSUE TITLE
falta de tradução e margem errada 

### ISSUE THREAD

**Issue by josueasas** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#27]
na área de permissões dos aplicativos está faltando traduções.
o texto passa por cima de outro texto.
na área de comentários quando vou escolher a data para o relatório os dias das semanas estão descritos com as iniciais em inglês (sun, mon, tue).
à um problema com as margens na área de permissões mas não sei se você é o responsável por cuidar disso.
Enviado do redmi note 7
![Screenshot_2021-01-04-02-54-56-092_com miui bugreport](https://user-images.githubusercontent.com/45245119/103505607-705a4a80-4e39-11eb-8447-3e4fe37683a2.jpg)
![Screenshot_2021-01-04-02-37-08-543_com miui securitycenter](https://user-images.githubusercontent.com/45245119/103505610-718b7780-4e39-11eb-8d40-d9a328c75d4c.jpg)
![Screenshot_2021-01-04-02-36-56-357_com miui securitycenter](https://user-images.githubusercontent.com/45245119/103505611-72240e00-4e39-11eb-84a6-a371a6b5a7f2.jpg)

**Comment by RicardoGuariento** [comment]
@josueasas qual versão da ROM você tá usando?

**Comment by josueasas** [comment]
@RicardoGuariento versão semanal 20.12.28

**Comment by RicardoGuariento** [comment]
@josueasas A linha que está em inglês realmente ainda não traduzi. 
Tem muita coisa pra traduzir e estou traduzindo aos poucos, quanto aos outros problemas, vou ver se consigo corrigir já.
Aviso aqui quando encontrar as linhas.
