### ISSUE TITLE
Aplicativo da XP Investimentos

### ISSUE THREAD

**Issue by GeorgePinheiroRamos** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#34]
Olá, o aplicativo da XP Investimentos não funciona nessa versão de 06/01/21.

**Comment by GeorgePinheiroRamos** [comment]
O aplicativo em questão não abre. Até a versão de 28/12/20 funcionava...

**Comment by KcNirvana** [comment]
Boas,
Isto é apenas o repositório de tradução.
Qualquer erro reportar em xiaomi.eu
Abraço
