### ISSUE TITLE
Vídeo travando e áudio com delay

### ISSUE THREAD

**Issue by klnreis** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#36]
Em todos os apps de vídeo no mi9t pro, as imagens passam sem áudio, depois o vídeo trava, o áudio segue até a parte que parou. Continua certo por algum momento, depois trava de novo.

**Comment by KcNirvana** [comment]
Boa tarde,
Se tiver uma rom Xiaomi.EU então reportar os bugs no fórum xiaomi.eu.
Aqui é apenas a tradução.
Abraço
