### ISSUE TITLE
Some pending translations (Algumas traduções pendentes)

### ISSUE THREAD

**Issue by DiorgenesS** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#39]
Good afternoon, I am using the Mi 10T with Miui 12.5, and I notice that some translations are pending, even if their repository is up to date, but the rom continues pulling from the strings from Portugal.
Example: Settings> Additional settings> wrong name: Wi-Fi Direct

Boa tarde, estou utilizando o Mi 10T com a Miui 12.5, e percebo que algumas traduções estão pendentes, mesmo que no seu repositório esteja atualizado, mas a rom continua puxando da strings de Portugal.
Exemplo: Configurações>Configurações adicionais> nome errado: Wi-Fi Directo

**Comment by RicardoGuariento** [comment]
Diogenes, é porque ainda falta bastante coisa para ser traduzida. O commit da MIUI 12.5 é gigantesco. 
Eu e a @thewhiteharlot estamos traduzindo aos poucos.
