### ISSUE TITLE
Erro de tradução

### ISSUE THREAD

**Issue by bryangrobmann** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#40]
Arquivo: Brazilian-Portuguese/main/MiuiSystemUI.apk/res/values-pt-rBR/strings.xml

    <string name="inline_turn_off_notifications">DesativarF notificações</string>

Desativar"F"

----------------------

Sugiro revisar o Xiaomi Health, eu configuro meu tipo sanguíneo para B+, mas na hora de apresentar, apresenta como B-

Não sei onde está o erro da tradução, se na tela de configurações ou se na hora de apresentar o tipo sanguíneo.

Vocês tem um grupo no Telegram ou Whatsapp onde posso colaborar reportando erros/sugestões de tradução? Facilitaria ao invés de ficar abrindo Issues.

Abraço!

**Comment by RicardoGuariento** [comment]
@bryangrobmann pode me chamar no Telegram 
https://t.me/rickguariento

**Comment by DiorgenesS** [comment]
@bryangrobmann o fator RH foi corrigido como você pode ver aqui: [fix fator RH](https://github.com/RicardoGuariento/MIUI-XML-12-BRAZILIAN/pull/47/commits/7edf19f1a8faac720ba06e7952cc20f5ea246da7) acho que na proxima atualização a tradução entrará em vigor
