### ISSUE TITLE
Erro de tradução em respostas rápidas

### ISSUE THREAD

**Issue by tonyjeffferson** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#45]
No app Telefone em configurações > configurações avançadas > Respostas rápidas,  a tradução está "Gravação de chamadas desativada"

**Comment by thewhiteharlot** [comment]
Não entendi, qual o erro?

**Comment by tonyjeffferson** [comment]
![WhatsApp Image 2021-02-02 at 20 04 44](https://user-images.githubusercontent.com/31293930/106674511-1bbe0280-6592-11eb-83cf-c5762e8d8fea.jpeg)

**Comment by thewhiteharlot** [comment]
E qual o erro?
