### ISSUE TITLE
DownloadProvider.apk e DownloadProviderUI.apk - Tradução PT-BR

### ISSUE THREAD

**Issue by KcNirvana** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#5]
Amigo, bom dia!

Eu não sei porque, mas os APKS DownloadProvider e DownloadProviderUI não assumem o idioma PT-BR no sistema, apenas o PT-PT. Eu já refiz a tradução do zero, já revi tudo e aparentemente não te nada de errado.
Você tem ideia do que possa ser?

Abraço!

**Comment by KcNirvana** [comment]
Boas
A mim parece-me bem.
![Screenshot_2020-05-04-13-04-58-669_com android providers downloads ui](https://user-images.githubusercontent.com/12718890/80965731-fb96c280-8e0a-11ea-8773-82f7313a359c.jpg)

É por causa do nome "Transferências"?
Que nome é que quer dar?
Abraço

**Comment by RicardoGuariento** [comment]
Então, para nós aqui, o certo é ficar como "Downloads". 
Inclusive já tem a string com o nome "Downloads" lá no XML, mas ainda sim ele assume o PT-PT.

Eu tô achando que, se deixar "Downloads", ele considera como igual ao que está em inglês e assume o PT-PT.

**Comment by KcNirvana** [comment]
Tive a validar e parece te tudo bem na tradução.
Só que no apk que foi na ROM não tem esta tag
![image](https://user-images.githubusercontent.com/12718890/80967355-26cee100-8e0e-11ea-8b1d-bc64bf9bb765.png)

Pode ser mesmo algum erro de quando foi feita a ROM.
Vamos esperar para a ROM desta semana se já tá corrigido.
Abraço

**Comment by RicardoGuariento** [comment]
Valeu! Obrigado!
