### ISSUE TITLE
Spotify player continua aparecendo

### ISSUE THREAD

**Issue by maalditogaah** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#56]
O player do spotify que fica na barra de notificação continua aparecendo mesmo fechando o spotify.
Ja reinstalei o aplicativo e continua acontecendo isso.
To usando a ultima versao da miui.eu disponivel pro poco f3
Algumas vezes a barra de notificação fica transparente tambem.

![Screenshot_2021-06-09-20-34-20-630_com miui home](https://user-images.githubusercontent.com/10039095/121442587-51b92c00-c962-11eb-83b5-1a750803bcc6.jpg)

![InkedScreenshot_2021-06-09-20-34-25-744_com miui home_LI](https://user-images.githubusercontent.com/10039095/121442554-46660080-c962-11eb-8142-4f86ad4c5fd4.jpg)

**Comment by maalditogaah** [comment]
Eu fecho o spotify, fecho do "aplicativos recentes" tambem, forço a parada dele e nao funciona. Quando removo manualmente da area de notificação ele some mas se eu bloquear/desbloquear a tela ele volta.

**Comment by KcNirvana** [comment]
Boas,
Isto aqui é um repositório de tradução, não é a secção de bugs da ROM.
Va a xiaomi.eu e exponha esse problema.
Obrigado.
