### ISSUE TITLE
String longa impossibilita a visualização do nível de bateria do Redmi Airdots 3

### ISSUE THREAD

**Issue by danilomazzaro** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#57]
PT-BR -> Quando em inglês, a string "case" é curta e possibilita a visualização da porcentagem de carga da bateria.
Em português, a string usada é "estojo de carregamento" e por ser muito comprida, a porcentagem da bateria fica fora do limite visível. Já experimentei apenas "Estojo" e deu certo, mas não creio que seja uma tradução apropriada, porém, em vários vídeos sobre fones TWS, as pessoas usam o termo "Case" mesmo e creio que seja um termo suficientemente difundido, pois assim é possível visualizar a porcentagem de bateria como demonstrado na imagem em anexo.

En -> In English, the string "case" is short and clearly allows the user to view the case battery info.
In Portuguese, the string used is "estojo de carregamento" and because it is very long, the battery info are in outside of the visible area. I've just tried "Estojo" and it worked, but I don't think it's an appropriate translation, but in several videos about TWS headphones in Brazil, most people use the term "Case" and I think it's a fairly widespread term, because that's shows the battery info as shown in the attached image

![sc-estojo](https://user-images.githubusercontent.com/13973005/123527485-5e55b800-d6b6-11eb-90f7-70fa892dd07a.jpg)

**Comment by DiorgenesS** [comment]
@danilomazzaro vou colocar "case"
