### ISSUE TITLE
Report Bug ligação Rdm Note 6 Pro

### ISSUE THREAD

**Issue by MthsOdilon** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#58]
olá, então sobre o Rdm Note 6 Pro, venho reportar que as vezes ele não recebe ligações, pra quem liga da como desligado, mesmo com o chip e tudo funcionando normalmente, descupe o incomodo. 

_Edit-_ na versão eu da miui _12._

**Comment by DiorgenesS** [comment]
@MthsOdilon aqui os reportes de bugs são referentes a tradução. Você deve reportar no fórum da ROM
