### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by befoda** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#59]
tô com um problema com o mi 9t que a tela sempre  Ativa não funciona e aparece sempre que o app permissões esta com falhas constantes

**Comment by DiorgenesS** [comment]
@befoda os erros a serem reportados aqui nesse repo devem ser sobre as traduções no idioma pt-br, bugs na ROM você deve reportar diretamente no fórum da xiaomi.eu
