### ISSUE TITLE
Falta de espaço

### ISSUE THREAD

**Issue by bryangrobmann** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#6]
Ricardo, como vai?

Na Barra de notificações sugiro mencionar a semana abreviada, ex: Seg. Ter. Qua., pois dependendo do conteúdo está invadido a escrita, conforme foto abaixo.

E também, a data está aparecendo mês e depois dia, acredito que ficaria melhor DD/MM, o que acha?

Abs!

![Screenshot_2020-05-04-08-03-32-659_com whatsapp](https://user-images.githubusercontent.com/64729763/80992139-719d2880-8e0f-11ea-96e2-721374f07066.jpg)

**Comment by RicardoGuariento** [comment]
@KcNirvana você sabe em qual APK está isso? Como altero esse formato de data?

**Comment by KcNirvana** [comment]
@RicardoGuariento 
https://github.com/RicardoGuariento/MIUI-XML-12-BRAZILIAN/blob/0f3d6176eea7028b60dedb06a9e14e398668ccdd/Brazilian-Portuguese/main/MiuiSystemUI.apk/res/values-pt-rBR/strings.xml#L2073
https://github.com/RicardoGuariento/MIUI-XML-12-BRAZILIAN/blob/0f3d6176eea7028b60dedb06a9e14e398668ccdd/Brazilian-Portuguese/main/MiuiSystemUI.apk/res/values-pt-rBR/strings.xml#L2074

São essas duas linhas

Se puser EEE, dd/MM fica Seg, 04/05
Se puser E, dd/MM fica S, 04/05

**Comment by RicardoGuariento** [comment]
@KcNirvana obrigado mais uma vez, amigo! Corrigi aqui.
