### ISSUE TITLE
Tradução errada no "Centro de Controle", botão "Uso de dados"

### ISSUE THREAD

**Issue by atotini** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#60]
Olá
Estou usando a MIUI.EU 12.0.7 e notei que o "Centro de Controle" está mostrando erroneamente um texto que parece ser um Aviso, mas que é somente um texto informativo.

Apesar da função de limite de dados móveis do meu celular estar Desligada, o Centro de Controle mostra a mensagem **"Acima do limite"** e a quantidade de dados utilizado desde o começo do mês.
Interessante notar que a cor de fundo do botão NÃO é de alerta, o que parece que a mensagem deveria ser apenas **"Uso de dados"** e a quantidade de dados utilizado.

Segue abaixo link com a imagem:
[](https://drive.google.com/file/d/1FEe9NzqdFGQZqIw9VHd99D1n_BTsMDcB/view?usp=sharing)

Um amigo está usando uma MIUI bem mais nova (12.6), mas a mensagem continua sendo "Acima do limite".

Obrigado

**Comment by DiorgenesS** [comment]
@atotini eu fiz algumas mudanças e você pode ver aqui: [correções](https://github.com/RicardoGuariento/MIUI-XML-12-BRAZILIAN/commit/1f6a8275d157d071c7eaa34263143efc371dc849#diff-b071fd605dc7adaf34bd42f2f8c32412377f3c8e288cd822c689673cd86656efL2247)

**Comment by atotini** [comment]
> @atotini eu fiz algumas mudanças e você pode ver aqui: [correções](https://github.com/RicardoGuariento/MIUI-XML-12-BRAZILIAN/commit/1f6a8275d157d071c7eaa34263143efc371dc849#diff-b071fd605dc7adaf34bd42f2f8c32412377f3c8e288cd822c689673cd86656efL2247)

Bom dia amigo

Pelo o que entendi das diferenças, ainda vai continuar mostrando a mensagem "Acima do limite" ...

Neste caso em especifico, no "Centro de Controle", limite de dados NÃO atingido, o correto não seria apenas printar "Dados utilizados" ou "Uso de dados". Porque o botão só mostra o total de dados utilizados mesmo, uma vez que não ativei o limitador. Ou então printar "Sem limite", pois de fato não existe limite de dados configurado.

São só algumas sugestões para melhorar a tradução da MIUI.EU, que por sinal já é muito boa.

Obrigado
Alex

**Comment by DiorgenesS** [comment]
@atotini me chama no telegram @dio_s
