### ISSUE TITLE
Ajudar no projeto

### ISSUE THREAD

**Issue by gss200610** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#61]
Como posso ajudar com a tradução?, fiz algumas pro projeto miuiVNa e estou atualizando, fazendo um merge desse git com novos arquivos da versão chinesa.

**Comment by DiorgenesS** [comment]
@gss200610 você pode sincronizar esse git e depois fazer o pull request ou falar com o @RicardoGuariento para ele te adicionar no repo e ai pode fazer as alterações sem a necessidade de permissão

**Comment by gss200610** [comment]
> @gss200610 você pode sincronizar esse git e depois fazer o pull request ou falar com o @RicardoGuariento para ele te adicionar no repo e ai pode fazer as alterações sem a necessidade de permissão

Mandei um email pra ele, estou aguardando resposta.Obrigado!

**Comment by DiorgenesS** [comment]
@gss200610 chama ele no telegram, creio que o retorno será mais rápido, no readme do repo tem

**Comment by gss200610** [comment]
Blz, obrigado

Em seg., 20 de set. de 2021 20:20, Diorgenes ***@***.***>
escreveu:
