### ISSUE TITLE
"Erro" na Central de Controle e no Painel de notificações - MIUI 12 on Xiaomi.EU

### ISSUE THREAD

**Issue by augustoperes1** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#7]
Bom, instalei recentemente a Xiaomi.EU 20.4.27, que é a única mais atual disponível para o Redmi Note 7 (lavender). E notei um bug logo quando instalei, porém não sei ao certo se é um bug na tradução ou bug em sistema mesmo, enfim... De qualquer modo estou reportando!

Nas prints mostra um erro de design que não consta na versão global em inglês.

![MUt02FR](https://user-images.githubusercontent.com/46403862/81089545-e2594900-8ed2-11ea-9bcc-a65b50e17706.jpg)

### **Na central de controle, no nome, creio que uma quebra de linha resolveria, eu acho**

![4XqluDC](https://user-images.githubusercontent.com/46403862/81089564-e84f2a00-8ed2-11ea-8dff-ed19e1cfec38.jpg)

**Comment by RicardoGuariento** [comment]
O ponto é que em Inglês fica como "Control center", ou seja, tem menos caracteres. Eu até pensei em mudar para "Acesso rápido", mas não sei se fica bom. Não sei também se uma quebra de linha ali iria jogar o conteúdo pra baixo ou iria ficar encavalado.

@KcNirvana @MardSilva o que acham?

Quanto ao segundo problema, eu já fiz a correção. É para ficar, por exemplo "Terça, 05/05".

**Comment by augustoperes1** [comment]
No caso da central de controle, creio que seja um erro de sistema mesmo, os desenvolvedores devem colocar uma "barreira" ali, de modo que a quebra de linha seja automática para palavras em outros idiomas, porém creio que "Acesso rápido" seja um nome apropriado...

**Edit 1:** E como você pode observar, essa versão é bem de teste, pois a fonte do sistema é a Roboto Light, diferentemente da fonte liberada nas prints oficiais da xiaomi

### **Print liberado pela xiaomi:** 

![control 2 - Imgur](https://user-images.githubusercontent.com/46403862/81100252-9adab900-8ee2-11ea-91de-b7bdeb379513.png)

### **Print citado na thread:**

![control](https://user-images.githubusercontent.com/46403862/81100287-ae861f80-8ee2-11ea-94f6-ac23e5d33217.jpg)

**Comment by MardSilva** [comment]
Creio que "Acesso rápido" seja um bom nome. Apesar de de forma "direta" o correto é 'Central de controle'. 

Sobre a quebra da linha, é aguardar e ver se será terá por padrão a quebra. 

Ou ponto importante sobre esse item é que se realmente, a Xiaomi lançar como 'Central de controle', ela deve criar essa 'quebra' e, posteriormente será editada/alterada.

**Comment by andrealbuquerk** [comment]
Poderia colocar apenas "Controles". Ficaria simples e esteticamente bonito

**Comment by RicardoGuariento** [comment]
"Controles" eu acho que ficaria bem legal.

**Comment by RicardoGuariento** [comment]
Eu achei bem zoado a maioria dos títulos e informações dos botões virem cortadas. Poderiam ter deixado mais uniforme esses textos.

**Comment by bryangrobmann** [comment]
Para mim fica normal, as pessoas usam a fonte muito grande (que vem por padrão), ou eu que uso muuuuito pequeno? rsrsrs.
![Screenshot_2020-05-05-17-11-23-832_com miui home](https://user-images.githubusercontent.com/64729763/81111593-b4383100-8ef3-11ea-92d4-8c3bc054757f.jpg)

**Comment by RicardoGuariento** [comment]
@bryangrobmann eu uso o DPI em 509, pra você ter ideia.

**Comment by RicardoGuariento** [comment]
![WhatsApp Image 2020-05-03 at 18 38 46 (1)](https://user-images.githubusercontent.com/46526008/81116453-c7e79580-8efb-11ea-8d42-c316ee2c389e.jpeg)
![WhatsApp Image 2020-05-03 at 18 38 46](https://user-images.githubusercontent.com/46526008/81116456-c8802c00-8efb-11ea-8d05-c7dc3b03d7aa.jpeg)

**Comment by RicardoGuariento** [comment]
Deixei como "Controles" conforme sugerido.
