### ISSUE TITLE
Problemas com Aplicativos

### ISSUE THREAD

**Issue by davisantana** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#8]
Olá vim por meio deste informar problemas com alguns aplicativos.

Aplicativo: CALCULADORA **(Não abre)**
Aplicativo: BANCO SANTANDER **(Abre mais não permite logar após atualizar para 20.4.30)**

Jogo: INJUSTICE GOD AMONG US **(Fecha sozinho após o carregamento)**

Aparelho: Mi9T
OS: MIUI 12 - 20.4.30

**Comment by RicardoGuariento** [comment]
O problema da calculadora já foi corrigido. Quanto aos outros problemas, não sei te dizer o que pode ser. Eu cuido apenas da tradução da ROM.
