### ISSUE TITLE
Dados móveis

### ISSUE THREAD

**Issue by RicardoGuariento** [RicardoGuariento/MIUI-XML-12-BRAZILIAN#9]
![Screenshot_2020-05-12-22-32-02-442_com miui home](https://user-images.githubusercontent.com/46526008/81761490-72cdf580-94a0-11ea-9710-229310296121.jpg)
@KcNirvana você sabe qual é a string no MiuiSystemUi para esses "Dados móveis"? Quero deixar só "Dados"

**Comment by KcNirvana** [comment]
Boas...
Aqui:
https://github.com/RicardoGuariento/MIUI-XML-12-BRAZILIAN/blob/ffab1118b3c678d9633a8c8e187a1367bf298e2b/Brazilian-Portuguese/main/MiuiSystemUI.apk/res/values-pt-rBR/strings.xml#L1317

**Comment by KcNirvana** [comment]
Já alteraste...
:)
